name: validate
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/
      - name: Setup Jobs
        id: setup-jobs
        shell: bash
        run: ./.github/workflows/scripts/setup-matrix.sh
    outputs:
      jobs: ${{ steps.setup-jobs.outputs.jobs }}
  validate:
    if: ${{ needs.setup.outputs.jobs }}
    needs: setup
    uses: ./.github/workflows/build.yml
    name: ${{ matrix.jobs.name }}
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.jobs) }}
    secrets: inherit
    with:
      matrix: ${{ toJSON(matrix.jobs.matrix) }}
