name: validate
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Action Validation
        shell: bash
        run: |
          npm install
          npm run build
          npm run tests
      - name: Setup Jobs
        id: setup-jobs
        uses: ./ # RageAgainstThePixel/job-builder
        with:
          build-options: ./.github/workflows/build-options.json
          group-by: 'unity-version' # Optional, defaults to the first property in the build options object
          job-name-prefix: 'Build' # Optional, defaults to empty string
      - name: Verify Job Output was generated
        run: |
          output=$(echo '${{ steps.setup-jobs.outputs.jobs }}' | jq -r '. | length')
          if [ -z "$output" ] || [ "$output" -eq 0 ]; then
            echo "No jobs were generated. Please check your build options.";
            exit 1;
          fi
        shell: bash
    outputs:
      jobs: ${{ steps.setup-jobs.outputs.jobs }}
  validate:
    if: ${{ needs.setup.outputs.jobs }}
    needs: setup
    name: ${{ matrix.jobs.name }}
    secrets: inherit
    permissions:
      contents: read
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.jobs) }}
      fail-fast: false
    uses: ./.github/workflows/build.yml
    with:
      matrix: ${{ toJSON(matrix.jobs.matrix) }}
